config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :admin, path: 'admin' do
    resources :customers, only: [:index, :show, :edit, :update, :destroy], as: :admin_customers
    resources :jitikais, only: [:new, :create, :index, :show, :edit, :update, :destroy], as: :admin_jitikais do
      post 'favorite' => 'jitikais#favorite_create'
      delete 'favorite' => 'jitikais#favorite_destroy'
    end
    resources :dusts, only: [:new, :create, :index, :show, :edit, :update, :destroy], as: :admin_dusts do
      post 'favorite' => 'dusts#favorite_create'
      delete 'favorite' => 'dusts#favorite_destroy'
    end
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy], as: :admin_posts do
      post 'favorite' => 'posts#favorite_create'
      delete 'favorite' => 'posts#favorite_destroy'
      resources :post_comments, only: [:create]
    end
    resources :events, only: [:new, :create, :index, :show, :edit, :update, :destroy], as: :admin_events do
      post 'favorite' => 'events#favorite_create'
      delete 'favorite' => 'events#favorite_destroy'
      resources :event_comments, only: [:create]
    end
    resources :topics, only: [:index, :edit, :create, :update], as: :admin_topics
    resource :favorites, only: [:create, :destroy]

  end

  scope module: :public do
    resources :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw]
    resources :jitikais, only: [:index, :show] do
      post 'favorite' => 'jitikais#favorite_create'
      delete 'favorite' => 'jitikais#favorite_destroy'
    end
    resources :dusts, only: [:index, :show] do
      post 'favorite' => 'dusts#favorite_create'
      delete 'favorite' => 'dusts#favorite_destroy'
    end
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      post 'favorite' => 'posts#favorite_create'
      delete 'favorite' => 'posts#favorite_destroy'
      resources :post_comments, only: [:create]
    end
    resources :events, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      post 'favorite' => 'events#favorite_create'
      delete 'favorite' => 'events#favorite_destroy'
      resources :event_comments, only: [:create]
    end
    resources :topics, only: [:index], as: :public_topics
    resource :favorites, only: [:create, :destroy]

  end

  root to: "homes#top"
  get "search" => "searches#search"
  get '/homes/about' => "homes#about",as: 'about'

end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :image
  belongs_to :admin, optional: true
  belongs_to :customer, optional: true
  has_many :event_comments, dependent: :destroy
  has_many :favorites, as: :favoriteable, dependent: :destroy
  scope :published, -> {where(is_published_flag: true)}
  scope :unpublished, -> {where(is_published_flag: false)}

  def favorited_by?(user,type)
    if type == :admin
      return favorites.exists?(admin_id: user.id)
    elsif type == :customer
      return favorites.exists?(customer_id: user.id)
    end
    false
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @event = Event.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @event = Event.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @event = Event.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @event = Event.where("title LIKE?","%#{word}%")
    else
      @event = Event.all
    end
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.admin_id = current_admin.id
    if @event.save
      redirect_to admin_event_path(@event.id)
    else
      @events = Event.all
      render :index
    end
  end

  def index
    @events = Event.published
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
    @event_comment = EventComment.new
  end

  def edit
    @event = Event.find(params[:id])
    if @event.admin == current_admin
      render :edit
    else
      redirect_to admin_events_path
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to admin_event_path(@event.id)
    else
      render :edit
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy if event
    redirect_to '/admin/events'
  end

  def favorite_create
    event = Event.find(params[:admin_event_id])
    if event.admin.!= current_admin
      event.favorites.create(admin_id: current_admin.id)
    end
    redirect_back fallback_location: root_path
  end

  def favorite_destroy
    @event = Event.find(params[:admin_event_id])
    if @event.admin.!= current_admin
      @event.favorites.find_by(admin_id: current_admin.id).destroy
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :body, :is_published_flag)
  end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/views/admin/events/_comment.html.erb
<%= form_with url: admin_event_event_comments_path(@event.id) do |f| %>
  <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>

app/views/admin/events/_comment_count.html.erb
<p>コメント件数：<%= @event.event_comments.count %></p>
<% @event.event_comments.each do |event_comment| %>
  <%= event_comment&.admin&.name || event_comment&.customer&.nickname %>
  <%= event_comment.created_at.strftime('%Y/%m/%d') %><%= event_comment.comment %>
<% end %>

app/views/admin/events/_favorite.html.erb
<% if @event.favorited_by?(current_admin,:admin) %>
  <p>
    <%= link_to admin_event_favorite_path(@event.id), method: :delete, remote: true do %>
      ♥<%= @event.favorites.count %> いいね
    <% end %>
  </p>
  <% else %>
  <p>
    <%= link_to admin_event_favorite_path(@event.id), method: :post, remote: true do %>
      ♡<%= @event.favorites.count %> いいね
    <% end %>
  </p>
<% end %>

app/views/admin/events/comment_create.js.erb
$('#comment-<%= @event.id %>').html("<%= j(render 'comment', event: @event) %>")

app/views/admin/events/edit.html.erb
<h1>投稿編集</h1>
<% if @event.errors.any? %>
  <%= @event.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @event, url: admin_event_path(@event), method: :patch do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit '再投稿' %>

<% end %>

<%= link_to "詳細", admin_event_path(@event.id) %>
<%= link_to "戻る", admin_events_path %>

app/views/admin/events/favorite_create.js.erb
$('#favorite-<%= @event.id %>').html("<%= j(render 'favorite', event: @event) %>")

app/views/admin/events/favorite_destroy.js.erb
$('#favorite-<%= @event.id %>').html("<%= j(render 'favorite', event: @event) %>")

app/views/admin/events/index.html.erb
<% @events.each do |event| %>
  <% if admin_signed_in? %>
    <%= link_to "管理者用削除", admin_event_path(event.id), method: :delete %>
  <% end %>
  <div>
    <%= link_to admin_event_path(event.id) do %>
      <%= event.title %>
    <% end %>
    <p>投稿者：<%= event.customer.nil? ? event.admin.name : event.customer.nickname %></p>
    <p><%= link_to "#{event.event_comments.count} コメント", admin_event_path(event.id) %></p>
  </div>
<% end %>

app/views/admin/events/new.html.erb
<%= form_with model: @event,url:admin_events_path do |f| %>
<div class="form-group">
  <label>
    <p>タイトル</p>
    <%= f.text_field :title %>
  </label>
</div>
<div class="form-group">
  <p>説明</p>
  <%= f.text_area :body %>
  <%= f.submit '投稿', class: "btn btn-success" %>
</div>
<div>
  <p>画像</p>
  <%= f.file_field :image, accept: "image/*" %>
</div>
<% end %>

app/views/admin/events/show.html.erb
<div>
  <p><%= @event.title %></p>
  <p><%= @event.body %></p>
  <% if @event.image.attached? %>
    <%= image_tag @event.get_image %>
  <% end %>
  <% if @event.customer.present? %>
  <p>投稿者：<%= @event.customer.nickname %></p>
  <% else %>
  <p>投稿者：<%= @event.admin.name %></p>
  <% end %>
  <p>投稿日：<%= @event.created_at.strftime('%Y/%m/%d') %></p>
  <% if @event.admin == current_admin %>
    <td><%= link_to "編集", edit_admin_event_path(@event.id) %></td>
    <td><%= link_to "削除", admin_event_path(@event), method: :delete %></td>
  <% end %>
  <div id="favorite-<%= @event.id %>">
  <%= render 'admin/events/favorite', event: @event %>
  </div>
</div>
<div id="comment_count-<%= @event.id %>">
  <%= render 'admin/events/comment_count', event: @event %>
</div>
<div id="comment-<%= @event.id %>">
  <%= render 'admin/events/comment', event: @event, event_comment: @event_comment %>
</div>













<div class="container mt-5">
  <div class='row justify-content-center'>
    <div class="col-md-10">

      <h3 class="mx-auto headline">マイページ</h3>

        <div class='row '>
          <div class="col-md-3 d-flex mt-3 mb-2 justify-content-between align-items-center">
            <h4 class="mb-0">登録情報</h4>
            <%= link_to "編集する", edit_customer_path, class: "btn d-flex align-items-center ms-3 btn-success" %>
          </div>
        </div>
        <div class='row'>
          <div class="mt-3">
            <table class="table table-bordered border-dark table-hover table-inverse custom-table">
              <tbody>
                <tr>
                  <th>氏名</th>
                  <td><%= @customer.name %></td>
                </tr>
                <tr>
                  <th>ニックネーム</th>
                  <td><%= @customer.nickname %></td>
                </tr>
                <tr>
                  <th>電話番号</th>
                  <td><%= @customer.telephone_number %></td>
                </tr>
                <tr>
                  <th>メールアドレス</th>
                  <td><%= @customer.email %></td>
                </tr>
              </tbody>
            </table>
          </div>

          <div class="col-md-3 d-flex mt-3 mb-2 justify-content-between align-items-stretch">
            <h4 class="mb-0">自身の投稿</h4>
              <div class='row'>
                <div class="mt-3">
                  <table class="table">
                    <tbody>
                      <% @posts.each do |post| %>
                        <div><%= link_to "#{post.title} ", post_path(post.id) %></div>
                      <% end %>
                      <% @events.each do |event| %>
                        <div><%= link_to "#{event.title} ", event_path(event.id) %></div>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>


          <div class="col-md-3 d-flex mt-3 mb-2 justify-content-between align-items-stretch">
            <h4 class="mb-0">お気に入り</h4>
              <div class='row'>
                <div class="mt-3">
                  <table class="table">
                    <tbody>
                      <% @customer.favorite_posts.each do | post| %>
                          <div>----<%= post.title %>----</div>
                      <% end %>
                      <% @customer.favorite_events.each do | event| %>
                          <div>----<%= event.title %>----</div>
                      <% end %>
                      <% @customer.favorite_jitikais.each do | jitikai| %>
                          <div>----<%= jitikai.title %>----</div>
                      <% end %>
                      <% @customer.favorite_dusts.each do | dust| %>
                          <div>----<%= dust.title %>----</div>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

          <div class="col-md-3 d-flex mt-3 mb-2 justify-content-between align-items-stretch">
            <h4 class="mb-0">コメント</h4>
              <div class='row'>
                <div class="mt-3">
                  <table class="table">
                    <tbody>
                      <% @customer.post_comments.each do |comment| %>
                          <div><%= link_to "#{comment.post.title} コメント", post_path(comment.post.id) %></div>
                      <% end %>
                      <% @customer.event_comments.each do |comment| %>
                          <div><%= link_to "#{comment.event.title} コメント", event_path(comment.event.id) %></div>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div><div class='row '>
          <div class="col-md-3 d-flex mt-3 mb-2 justify-content-between align-items-center">
            <h4 class="mb-0">登録情報</h4>
            <%= link_to "編集する", edit_customer_path, class: "btn d-flex align-items-center ms-3 btn-success" %>
          </div>
        </div>
        <div class='row'>
          <div class="mt-3">
            <table class="table table-bordered border-dark table-hover table-inverse custom-table">
              <tbody>
                <tr>
                  <th>氏名</th>
                  <td><%= @customer.name %></td>
                </tr>
                <tr>
                  <th>ニックネーム</th>
                  <td><%= @customer.nickname %></td>
                </tr>
                <tr>
                  <th>電話番号</th>
                  <td><%= @customer.telephone_number %></td>
                </tr>
                <tr>
                  <th>メールアドレス</th>
                  <td><%= @customer.email %></td>
                </tr>
              </tbody>
            </table>
          </div>

          <div class="col-md-3 d-flex mt-3 mb-2 justify-content-between align-items-stretch">
            <h4 class="mb-0">自身の投稿</h4>
              <div class='row'>
                <div class="mt-3">
                  <table class="table">
                    <tbody>
                      <% @posts.each do |post| %>
                        <div><%= link_to "#{post.title} ", post_path(post.id) %></div>
                      <% end %>
                      <% @events.each do |event| %>
                        <div><%= link_to "#{event.title} ", event_path(event.id) %></div>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>


          <div class="col-md-3 d-flex mt-3 mb-2 justify-content-between align-items-stretch">
            <h4 class="mb-0">お気に入り</h4>
              <div class='row'>
                <div class="mt-3">
                  <table class="table">
                    <tbody>
                      <% @customer.favorite_posts.each do | post| %>
                          <div>----<%= post.title %>----</div>
                      <% end %>
                      <% @customer.favorite_events.each do | event| %>
                          <div>----<%= event.title %>----</div>
                      <% end %>
                      <% @customer.favorite_jitikais.each do | jitikai| %>
                          <div>----<%= jitikai.title %>----</div>
                      <% end %>
                      <% @customer.favorite_dusts.each do | dust| %>
                          <div>----<%= dust.title %>----</div>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
<div class="col-md-3 d-flex mt-3 mb-2 justify-content-between align-items-stretch">
            <h4 class="mb-0">お気に入り</h4>
              <div class='row'>
                <div class="mt-3">
                  <table class="table">
                    <tbody>
                      <% @customer.favorite_posts.each do | post| %>
                          <div>----<%= post.title %>----</div>
                      <% end %>
                      <% @customer.favorite_events.each do | event| %>
                          <div>----<%= event.title %>----</div>
                      <% end %>
                      <% @customer.favorite_jitikais.each do | jitikai| %>
                          <div>----<%= jitikai.title %>----</div>
                      <% end %>
                      <% @customer.favorite_dusts.each do | dust| %>
                          <div>----<%= dust.title %>----</div>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

          <div class="col-md-3 d-flex mt-3 mb-2 justify-content-between align-items-stretch">
            <h4 class="mb-0">コメント</h4>
              <div class='row'>
                <div class="mt-3">
                  <table class="table">
                    <tbody>
                      <% @customer.post_comments.each do |comment| %>
                          <div><%= link_to "#{comment.post.title} コメント", post_path(comment.post.id) %></div>
                      <% end %>
                      <% @customer.event_comments.each do |comment| %>
                          <div><%= link_to "#{comment.event.title} コメント", event_path(comment.event.id) %></div>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div><div class="col-md-3 d-flex mt-3 mb-2 justify-content-between align-items-stretch">
            <h4 class="mb-0">お気に入り</h4>
              <div class='row'>
                <div class="mt-3">
                  <table class="table">
                    <tbody>
                      <% @customer.favorite_posts.each do | post| %>
                          <div>----<%= post.title %>----</div>
                      <% end %>
                      <% @customer.favorite_events.each do | event| %>
                          <div>----<%= event.title %>----</div>
                      <% end %>
                      <% @customer.favorite_jitikais.each do | jitikai| %>
                          <div>----<%= jitikai.title %>----</div>
                      <% end %>
                      <% @customer.favorite_dusts.each do | dust| %>
                          <div>----<%= dust.title %>----</div>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

          <div class="col-md-3 d-flex mt-3 mb-2 justify-content-between align-items-stretch">
            <h4 class="mb-0">コメント</h4>
              <div class='row'>
                <div class="mt-3">
                  <table class="table">
                    <tbody>
                      <% @customer.post_comments.each do |comment| %>
                          <div><%= link_to "#{comment.post.title} コメント", post_path(comment.post.id) %></div>
                      <% end %>
                      <% @customer.event_comments.each do |comment| %>
                          <div><%= link_to "#{comment.event.title} コメント", event_path(comment.event.id) %></div>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

          <div class="col-md-3 d-flex mt-3 mb-2 justify-content-between align-items-stretch">
            <h4 class="mb-0">自身の投稿</h4>
              <div class='row'>
                <div class="mt-3">
                  <table class="table">
                    <tbody>
                      <% @posts.each do |post| %>
                        <div><%= link_to "#{post.title} ", post_path(post.id) %></div>
                      <% end %>
                      <% @events.each do |event| %>
                        <div><%= link_to "#{event.title} ", event_path(event.id) %></div>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

    </div>
  </div>
</div>