config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :admin, path: 'admin' do
    resources :customers, only: [:index, :show, :edit, :update, :destroy], as: :admin_customers
    resources :jitikais, only: [:new, :create, :index, :show, :edit, :update, :destroy], as: :admin_jitikais do
      post 'favorite' => 'jitikais#favorite_create'
      delete 'favorite' => 'jitikais#favorite_destroy'
    end
    resources :dusts, only: [:new, :create, :index, :show, :edit, :update, :destroy], as: :admin_dusts do
      post 'favorite' => 'dusts#favorite_create'
      delete 'favorite' => 'dusts#favorite_destroy'
    end
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy], as: :admin_posts do
      post 'favorite' => 'posts#favorite_create'
      delete 'favorite' => 'posts#favorite_destroy'
      resources :post_comments, only: [:create]
    end
    resources :events, only: [:new, :create, :index, :show, :edit, :update, :destroy], as: :admin_events do
      post 'favorite' => 'events#favorite_create'
      delete 'favorite' => 'events#favorite_destroy'
      resources :event_comments, only: [:create]
    end
    resources :topics, only: [:index, :edit, :create, :update], as: :admin_topics
    resource :favorites, only: [:create, :destroy]

  end

  scope module: :public do
    resources :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw]
    resources :jitikais, only: [:index, :show] do
      post 'favorite' => 'jitikais#favorite_create'
      delete 'favorite' => 'jitikais#favorite_destroy'
    end
    resources :dusts, only: [:index, :show] do
      post 'favorite' => 'dusts#favorite_create'
      delete 'favorite' => 'dusts#favorite_destroy'
    end
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      post 'favorite' => 'posts#favorite_create'
      delete 'favorite' => 'posts#favorite_destroy'
      resources :post_comments, only: [:create]
    end
    resources :events, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      post 'favorite' => 'events#favorite_create'
      delete 'favorite' => 'events#favorite_destroy'
      resources :event_comments, only: [:create]
    end
    resources :topics, only: [:index], as: :public_topics
    resource :favorites, only: [:create, :destroy]

  end

  root to: "homes#top"
  get "search" => "searches#search"
  get '/homes/about' => "homes#about",as: 'about'

end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :customer, optional: true
  belongs_to :admin, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :favorites, as: :favoriteable, dependent: :destroy
  scope :published, -> {where(is_published_flag: true)}
  scope :unpublished, -> {where(is_published_flag: false)}

  def favorited_by?(user,type)
    if type == :admin
      return favorites.exists?(admin_id: user.id)
    elsif type == :customer
      return favorites.exists?(customer_id: user.id)
    end
    false
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @post = Post.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.admin_id = current_admin.id
    if @post.save
      redirect_to admin_post_path(@post.id)
    else
      @posts = Post.published
      render :index
    end
  end

  def index
    @posts = Post.published
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
    if @post.admin == current_admin
      render :edit
    else
      redirect_to admin_posts_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to admin_post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy if post
    redirect_to '/admin/posts'
  end

  def favorite_create
    post = Post.find(params[:admin_post_id])
    if post.admin.!= current_admin
      post.favorites.create(admin_id: current_admin.id)
    end
    redirect_back fallback_location: root_path
  end

  def favorite_destroy
    @post = Post.find(params[:admin_post_id])
    if @post.admin.!= current_admin
      @post.favorites.find_by(admin_id: current_admin.id).destroy
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :is_published_flag)
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_comment.html.erb
<%= form_with url: admin_post_post_comments_path(@post.id) do |f| %>
  <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>

app/views/admin/posts/_comment_count.html.erb
<p>コメント件数：<%= @post.post_comments.count %></p>
<% @post.post_comments.each do |post_comment| %>
  <%= post_comment&.admin&.name || post_comment&.customer&.nickname %>
  <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
<% end %>

app/views/admin/posts/_favorite.html.erb
<% if @post.favorited_by?(current_admin, :admin) %>
  <p>
    <%= link_to admin_post_favorite_path(@post.id), method: :delete, remote: true do %>
      ♥<%= @post.favorites.count %> いいね
    <% end %>
  </p>
  <% else %>
  <p>
    <%= link_to admin_post_favorite_path(@post.id), method: :post, remote: true do %>
      ♡<%= @post.favorites.count %> いいね
    <% end %>
  </p>
<% end %>

app/views/admin/posts/comment_create.js.erb
$('#comment-<%= @post.id %>').html("<%= j(render 'comment', post: @post) %>")

app/views/admin/posts/edit.html.erb
<h1>投稿編集</h1>
<% if @post.errors.any? %>
  <%= @post.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @post, url: admin_post_path(@post), method: :patch do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit '再投稿' %>

<% end %>

<%= link_to "詳細", admin_post_path(@post.id) %>
<%= link_to "戻る", admin_posts_path %>

app/views/admin/posts/favorite_create.js.erb
$('#favorite-<%= @post.id %>').html("<%= j(render 'favorite', post: @post) %>")

app/views/admin/posts/favorite_destroy.js.erb
$('#favorite-<%= @post.id %>').html("<%= j(render 'favorite', post: @post) %>")

app/views/admin/posts/index.html.erb
<% @posts.each do |post| %>
  <% if admin_signed_in? %>
    <%= link_to "管理者用削除", admin_post_path(post.id), method: :delete %>
  <% end %>
  <div>
    <%= link_to admin_post_path(post.id) do %>
      <%= post.title %>
    <% end %>
    <p>投稿者：<%= post.admin.present? ? post.admin.name : post.customer.nickname %></p>
    <p><%= link_to "#{post.post_comments.count} コメント", admin_post_path(post.id) %></p>
  </div>
<% end %>

app/views/admin/posts/new.html.erb
<%= form_with model: @post,url:admin_posts_path do |f| %>
<div class="form-group">
  <label>
    <p>タイトル</p>
    <%= f.text_field :title %>
  </label>
</div>
<div class="form-group">
  <p>説明</p>
  <%= f.text_area :body %>
  <%= f.submit '投稿', class: "btn btn-success" %>
</div>
<div>
  <p>画像</p>
  <%= f.file_field :image, accept: "image/*" %>
</div>
<div>
  <p>公開設定</p>
  <%= f.label :is_published_flag, "公開", value: true %>
  <%= f.radio_button :is_published_flag, 'true' %>
</div>
<div>
  <%= f.label :is_published_flag, "非公開", value: false %>
  <%= f.radio_button :is_published_flag,'false' %>
</div>
<% end %>

app/views/admin/posts/show.html.erb
<div>
  <p><%= @post.title %></p>
  <p><%= @post.body %></p>
  <% if @post.image.attached? %>
    <%= image_tag @post.get_image %>
  <% end %>
  <% if @post.customer.present? %>
  <p>投稿者：<%= @post.customer.nickname %></p>
  <% else %>
  <p>投稿者：<%= @post.admin.name %></p>
  <% end %>
  <p>投稿日：<%= @post.created_at.strftime('%Y/%m/%d') %></p>
  <% if @post.admin == current_admin %>
    <td><%= link_to "編集", edit_admin_post_path(@post.id) %></td>
    <td><%= link_to "削除", admin_post_path(@post), method: :delete %></td>
  <% end %>
  <div id="favorite-<%= @post.id %>">
  <%= render 'admin/posts/favorite', post: @post %>
  </div>
</div>
<div id="comment_count-<%= @post.id %>">
  <%= render 'admin/posts/comment_count', post: @post %>
</div>
<div id="comment-<%= @post.id %>">
  <%= render 'admin/posts/comment', post: @post, post_comment: @post_comment %>
</div>