config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :admin, path: 'admin' do
    resources :customers, only: [:index, :show, :edit, :update, :destroy], as: :admin_customers
    resources :jitikais, only: [:new, :create, :index, :show, :edit, :update, :destroy], as: :admin_jitikais do
      post 'favorite' => 'jitikais#favorite_create'
      delete 'favorite' => 'jitikais#favorite_destroy'
    end
    resources :dusts, only: [:new, :create, :index, :show, :edit, :update, :destroy], as: :admin_dusts do
      post 'favorite' => 'dusts#favorite_create'
      delete 'favorite' => 'dusts#favorite_destroy'
    end
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy], as: :admin_posts do
      post 'favorite' => 'posts#favorite_create'
      delete 'favorite' => 'posts#favorite_destroy'
      resources :post_comments, only: [:create]
    end
    resources :events, only: [:new, :create, :index, :show, :edit, :update, :destroy], as: :admin_events do
      post 'favorite' => 'events#favorite_create'
      delete 'favorite' => 'events#favorite_destroy'
      resources :event_comments, only: [:create]
    end
    resources :topics, only: [:index, :edit, :create, :update], as: :admin_topics
    resource :favorites, only: [:create, :destroy]

  end

  scope module: :public do
    resources :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw]
    resources :jitikais, only: [:index, :show] do
      post 'favorite' => 'jitikais#favorite_create'
      delete 'favorite' => 'jitikais#favorite_destroy'
    end
    resources :dusts, only: [:index, :show] do
      post 'favorite' => 'dusts#favorite_create'
      delete 'favorite' => 'dusts#favorite_destroy'
    end
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      post 'favorite' => 'posts#favorite_create'
      delete 'favorite' => 'posts#favorite_destroy'
      resources :post_comments, only: [:create]
    end
    resources :events, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      post 'favorite' => 'events#favorite_create'
      delete 'favorite' => 'events#favorite_destroy'
      resources :event_comments, only: [:create]
    end
    resources :topics, only: [:index], as: :public_topics
    resource :favorites, only: [:create, :destroy]

  end

  root to: "homes#top"
  get "search" => "searches#search"
  get '/homes/about' => "homes#about",as: 'about'

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  
  end
  def about
    
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class="container mt-5">
  <div class='row justify-content-center mb-4'>
    <h1><strong>About</strong></h1>
  </div>
  <div class="row text-center justify-content-center mb-4">
    <p>このサイトはアートホームという自治会に属している方のみ使える情報掲示板です。<br>自治会連絡では避難訓練や改修工事などの自治会からのお知らせを<br>掲示板では自治会所属の皆様のコミュニティサイトとして<br>イベント連絡では自治会近辺のイベントの情報を<br>ごみの日では自治会でのごみの出し方について<br>情報を掲載したいと思います。</p>
  </div>
</div>

app/views/homes/top.html.erb
<div class="row">
  <%= link_to "ログイン", new_customer_session_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
</div>
<div class="row">
  <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in" %>
</div>
<div class="row">
  <%= link_to "ゲストログイン（閲覧用）", customers_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
</div>
<div class="row">
<%= link_to "管理者ログイン", new_admin_session_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
</div>