config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :admin, path: 'admin' do
    resources :customers, only: [:index, :show, :edit, :update, :destroy], as: :admin_customers
    resources :jitikais, only: [:new, :create, :index, :show, :edit, :update, :destroy], as: :admin_jitikais do
      post 'favorite' => 'jitikais#favorite_create'
      delete 'favorite' => 'jitikais#favorite_destroy'
    end
    resources :dusts, only: [:new, :create, :index, :show, :edit, :update, :destroy], as: :admin_dusts do
      post 'favorite' => 'dusts#favorite_create'
      delete 'favorite' => 'dusts#favorite_destroy'
    end
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy], as: :admin_posts do
      post 'favorite' => 'posts#favorite_create'
      delete 'favorite' => 'posts#favorite_destroy'
      resources :post_comments, only: [:create]
    end
    resources :events, only: [:new, :create, :index, :show, :edit, :update, :destroy], as: :admin_events do
      post 'favorite' => 'events#favorite_create'
      delete 'favorite' => 'events#favorite_destroy'
      resources :event_comments, only: [:create]
    end
    resources :topics, only: [:index, :edit, :create, :update], as: :admin_topics
    resource :favorites, only: [:create, :destroy]

  end

  scope module: :public do
    resources :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw]
    resources :jitikais, only: [:index, :show] do
      post 'favorite' => 'jitikais#favorite_create'
      delete 'favorite' => 'jitikais#favorite_destroy'
    end
    resources :dusts, only: [:index, :show] do
      post 'favorite' => 'dusts#favorite_create'
      delete 'favorite' => 'dusts#favorite_destroy'
    end
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      post 'favorite' => 'posts#favorite_create'
      delete 'favorite' => 'posts#favorite_destroy'
      resources :post_comments, only: [:create]
    end
    resources :events, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      post 'favorite' => 'events#favorite_create'
      delete 'favorite' => 'events#favorite_destroy'
      resources :event_comments, only: [:create]
    end
    resources :topics, only: [:index], as: :public_topics
    resource :favorites, only: [:create, :destroy]

  end

  root to: "homes#top"
  get "search" => "searches#search"
  get '/homes/about' => "homes#about",as: 'about'

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg text-center navbar-dark bg-dark">
  <div class="collapse navbar-collapse">
    <% if customer_signed_in? %>
    <div class="row d-flex justify-content-around align-items-center col-md-6 ms-5">
      <div class="navbar navbar-brand">
        <%= link_to root_path do %>
          <%= image_tag 'logo.jpg', size: '70x70' %>
        <% end %>
      </div>
      <h5 style="color: white;">ようこそ、<%= current_customer.name %>さん</h5>
    </div>
    <% elsif admin_signed_in? %>
    <div class="row d-flex justify-content-around align-items-center col-md-6 ms-5">
      <div class="navbar navbar-brand">
        <%= link_to root_path do %>
          <%= image_tag 'logo.jpg', size: '70x70' %>
        <% end %>
      </div>
    </div>
    <% else %>
      <div class="navbar navbar-brand ms-5">
        <%= link_to root_path do %>
          <%= image_tag 'logo.jpg', size: '70x70' %>
        <% end %>
        <div></div>
      </div>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>アートホーム情報板</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Jouhouban", root_path, class: "navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <li class="nav-item">
                <%= link_to public_topics_path, class: "text-light" do%>
                Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to customer_path(current_customer.id), class: "text-light" do%>
                マイページ
                <% end %>
                <li class="nav-item">
                <%= link_to destroy_customer_session_path, method: :delete ,class: "nav-link text-light" do%>
                ログアウト
                <% end %>
              </li>
              <% unless current_customer.guest? %>
              <li class="nav-item">
                <%= link_to new_post_path, class: "text-light" do%>
                掲示板に投稿
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_event_path, class: "text-light" do%>
                イベントに投稿
                <% end %>
              </li>
              <% end %>
            <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to admin_topics_path, class: "text-light" do%>
                Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_customers_path , class: "nav-link text-light" do %>
                登録者一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_admin_post_path, class: "text-light" do%>
                掲示板に投稿
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_admin_event_path, class: "text-light" do%>
                イベントに投稿
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_admin_jitikai_path, class: "text-light" do%>
                自治会掲示板に投稿
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_admin_dust_path, class: "text-light" do%>
                ごみ捨てに投稿
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-light" do %>
                ログアウト
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to about_path, class: "nav-link text-light" do %>
                About
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_topics_path, class: "text-light" do%>
                Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_customer_registration_path, class: "text-light" do%>
                新規登録
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_customer_session_path, class: "text-light" do%>
                ログイン
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <% if customer_signed_in? %>
      <div class="search_form">
        <%= form_with url: search_path, local: true, method: :get do |f| %>
          <%= f.text_field :word %>
          <%= f.select :range, options_for_select([['Post'], ['Event'],['Jitikai'],['Dust']]) %>
          <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
          <%= f.submit "検索", class: "btn btn-primary" %>
    　　<% end %>
        </div>
      <% end %>
    </header>
    <main class="mb-auto">
      <p id="notice"><%= flash[:notice] %></p>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <P>CopyRight アートホーム</P>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>